### ISSUE TITLE
Cursor Focus wenn sich die Suchbox öffnet

### ISSUE THREAD

**Issue by EuropaBuch** [maexware/ajaxsearch#1]
Der Cursor sollte in der sich öffnenden Suchbox automatisch ins Eingabefeld springen. Denn wenn derweil noch getippt wird, wird der User an der Stelle unterbrochen.

**Comment by maexware-andi** [comment]
Mit letztem commit wurde der autofocus in das Such Modal eingebaut. Bitte beachten das es hier sich um ein JS handelt und somit der Browsercache geleert werden muss.
