### ISSUE TITLE
Wenn mehr als ein Suchbegriff kein Ergebnis

### ISSUE THREAD

**Issue by EuropaBuch** [maexware/ajaxsearch#2]
Werden zwei oder mehr mit einer Leertaste getrennte Suchbegriffe eingegeben, bekomm ich kein Ergebnis (nicht mals die Meldung das es kein Ergebnis gibt).

Ich benutze OXID 6.1 CE, PHP 7.3, 10.1.37-MariaDB

**Comment by maexware-andi** [comment]
Durch letzten Commit wurde das Handling hierzu angepasst. Nun wird bei leeren Ergebnissen dies angezeigt und bei mehreren Suchbegriffen diese kombiniert angezeigt.
